# Generated by Django 4.2.6 on 2025-01-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_org', models.CharField(max_length=255)),
                ('client_desig', models.CharField(max_length=255)),
                ('client_mobile', models.CharField(max_length=255)),
                ('client_address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_description', models.CharField(max_length=255)),
                ('brand_image', models.ImageField(upload_to='images/brand/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_description', models.CharField(max_length=255)),
                ('cat_image', models.ImageField(upload_to='images/category/')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_org', models.CharField(max_length=255)),
                ('supplier_desig', models.CharField(max_length=255)),
                ('supplier_mobile', models.CharField(max_length=255)),
                ('supplier_address', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_model', models.CharField(max_length=255, null=True)),
                ('item_description', models.CharField(max_length=255, null=True)),
                ('item_sprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item_pprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='images/product/')),
                ('created_at', models.DateTimeField(null=True)),
                ('brand_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itembrand')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itemcategory')),
            ],
        ),
    ]
