# Generated by Django 4.2.6 on 2025-01-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0002_alter_itembrand_brand_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porder_total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('porder_discount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('porder_status', models.CharField(max_length=255)),
                ('porder_note', models.CharField(max_length=255)),
                ('porder_create_time', models.DateTimeField(null=True)),
                ('porder_update_time', models.DateTimeField(null=True)),
                ('porder_create_by', models.CharField(max_length=255)),
                ('porder_update_by', models.CharField(max_length=255)),
                ('supplier_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='itme_alert_qty',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='itme_barcode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='itme_sku',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='itme_status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='itme_unit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.CharField(max_length=255)),
                ('payment_status', models.CharField(max_length=255)),
                ('payment_time', models.DateTimeField(null=True)),
                ('payment_update_time', models.DateTimeField(null=True)),
                ('payment_create_by', models.CharField(max_length=255)),
                ('payment_update_by', models.CharField(max_length=255)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itme_unit', models.CharField(max_length=255)),
                ('itme_qty', models.CharField(max_length=255)),
                ('item_sprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item_pprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itemproduct')),
                ('porder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.purchaseorder')),
            ],
        ),
    ]
