# Generated by Django 4.2.6 on 2025-01-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0004_rename_supplier_name_purchaseorder_supplier_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itme_unit', models.CharField(max_length=255)),
                ('itme_qty', models.PositiveBigIntegerField(default=1)),
                ('item_sprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('item_pprice', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='porder_create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='porder_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseDetails',
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itemproduct'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='porder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.purchaseorderitem'),
        ),
    ]
