# Generated by Django 4.2.6 on 2025-01-16 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0005_purchaseorderitem_alter_itemproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_desig',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_org',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='itembrand',
            name='brand_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='category_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='brand_name',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itembrand'),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='item_description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='item_model',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='item_pprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='item_sprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='itme_alert_qty',
            field=models.CharField(blank=True, default=0, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='itme_barcode',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='itme_sku',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='itme_status',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='itme_unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='porder_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='porder_note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='porder_status',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='porder_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item_pprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='item_sprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='itme_unit',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_desig',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_org',
            field=models.CharField(default='', max_length=100),
        ),
    ]
