# Generated by Django 4.2.6 on 2025-01-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0007_alter_itemproduct_brand_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=20)),
                ('Unit_description', models.CharField(default='Default', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='itme_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
