# Generated by Django 4.2.6 on 2025-01-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0009_rename_unit_description_itemunit_unit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='porder_status',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
