# Generated by Django 4.2.6 on 2025-02-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0013_alter_itemproduct_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='item_sprice',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='itme_unit',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='porder_note',
            field=models.CharField(default='', max_length=500),
        ),
    ]
