# Generated by Django 4.2.6 on 2025-02-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0014_remove_purchaseorderitem_item_sprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_address',
            field=models.CharField(default='Slef', max_length=400),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_desig',
            field=models.CharField(default='Slef', max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_org',
            field=models.CharField(default='Slef', max_length=100),
        ),
    ]
