# Generated by Django 4.2.6 on 2025-02-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0015_alter_supplier_supplier_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitem',
            old_name='itme_qty',
            new_name='item_qty',
        ),
    ]
