# Generated by Django 4.2.6 on 2025-02-10 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0019_alter_purchaseorderitem_porder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='porder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_sl', to='business_apps.purchaseorder'),
        ),
    ]
