# Generated by Django 4.2.6 on 2025-02-16 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_apps', '0023_salesorder_alter_purchasepayment_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_description', models.CharField(default='', max_length=255)),
                ('service_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('service_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorder_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('sorder_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('sorder_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('sorder_status', models.CharField(choices=[('1', 'Received'), ('2', 'Pending'), ('3', 'Ordered'), ('4', 'Cancel')], default=3, max_length=1)),
                ('sorder_note', models.CharField(default='', max_length=500)),
                ('sorder_create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('sorder_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.clients')),
                ('service_create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_user', to=settings.AUTH_USER_MODEL)),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.service')),
                ('service_update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qty', models.PositiveBigIntegerField(default=1)),
                ('item_pprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('item_sprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('item_alert_qty', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('item_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itemproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ServicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_type', models.CharField(choices=[('1', 'Cash'), ('2', 'Card'), ('3', 'Due'), ('4', 'Others')], default=1, max_length=1)),
                ('payment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('payment_create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_service_user', to=settings.AUTH_USER_MODEL)),
                ('payment_update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_service_update', to=settings.AUTH_USER_MODEL)),
                ('sorder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.serviceorder')),
            ],
        ),
    ]
