# Generated by Django 4.2.6 on 2025-10-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_payment_updated_at_payment_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'ordering': ['purchase', 'product']},
        ),
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['module', 'name'], 'verbose_name': 'Transaction Type', 'verbose_name_plural': 'Transaction Types'},
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='serials',
            field=models.ManyToManyField(blank=True, related_name='purchase_items', to='products.productserial'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='code',
            field=models.CharField(help_text="Internal identifier, e.g. 'complete', 'cancel'", max_length=30),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(help_text="UI label, e.g. 'কম্প্লিট', 'ক্যানসেল'", max_length=50),
        ),
    ]
