# Generated by Django 4.2.6 on 2025-01-17 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_org', models.CharField(default='', max_length=100)),
                ('client_desig', models.CharField(default='', max_length=100)),
                ('client_mobile', models.CharField(default='', max_length=20)),
                ('client_address', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_description', models.CharField(default='', max_length=255)),
                ('brand_image', models.ImageField(default='images/default.png', upload_to='images/brand/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_description', models.CharField(default='', max_length=255)),
                ('cat_image', models.ImageField(default='images/default.png', upload_to='images/category/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_model', models.CharField(default='', max_length=255, null=True)),
                ('item_description', models.CharField(default='', max_length=255, null=True)),
                ('itme_unit', models.CharField(blank=True, max_length=255, null=True)),
                ('itme_sku', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('itme_alert_qty', models.CharField(blank=True, default=0, max_length=255, null=True)),
                ('itme_barcode', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('item_sprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('item_pprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('item_image', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/product/')),
                ('itme_status', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_apps.itembrand')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_apps.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porder_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('porder_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('porder_status', models.CharField(default='', max_length=255)),
                ('porder_note', models.CharField(default='', max_length=255)),
                ('porder_create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('porder_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('porder_create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='o_create_user', to=settings.AUTH_USER_MODEL)),
                ('porder_update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='o_create_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itme_unit', models.CharField(default='', max_length=255)),
                ('itme_qty', models.PositiveBigIntegerField(default=1)),
                ('item_sprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('item_pprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_apps.itemproduct')),
                ('porder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_apps.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('supplier_org', models.CharField(default='', max_length=100)),
                ('supplier_desig', models.CharField(default='', max_length=100)),
                ('supplier_mobile', models.CharField(default='', max_length=20)),
                ('supplier_address', models.CharField(default='', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_status', models.CharField(max_length=20)),
                ('payment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_apps.purchaseorderitem')),
                ('payment_create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_create_user', to=settings.AUTH_USER_MODEL)),
                ('payment_update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_create_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop_apps.supplier'),
        ),
    ]
