# Generated by Django 4.2.6 on 2025-02-10 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_customer_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
