# Generated by Django 4.2.6 on 2025-09-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_modulegroup_module_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_accordion',
            field=models.BooleanField(default=False),
        ),
    ]
