# Generated by Django 4.2.6 on 2025-12-02 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='class_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
