# Generated by Django 4.2.6 on 2025-12-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_module_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
