# Generated by Django 4.2.6 on 2025-12-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_module_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
