# Generated by Django 4.2.6 on 2025-12-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_module_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='icon_unicode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
