# Generated by Django 4.2.6 on 2025-12-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_module_icon_unicode'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulegroup',
            name='icon_unicode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
