# Generated by Django 4.2.6 on 2025-08-25 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ব্র্যান্ড নাম')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='লোগো')),
                ('origin_country', models.CharField(blank=True, max_length=100, verbose_name='দেশ')),
            ],
            options={
                'verbose_name': 'ব্র্যান্ড',
                'verbose_name_plural': 'ব্র্যান্ড তালিকা',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ক্যাটাগরি নাম')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='বর্ণনা')),
            ],
            options={
                'verbose_name': 'ক্যাটাগরি',
                'verbose_name_plural': 'ক্যাটাগরি তালিকা',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ইউনিট নাম')),
                ('symbol', models.CharField(max_length=20, verbose_name='প্রতীক')),
                ('description', models.TextField(blank=True, verbose_name='বর্ণনা')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='মূল ইউনিটের সাথে গুণফল')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
            ],
            options={
                'verbose_name': 'ইউনিট',
                'verbose_name_plural': 'ইউনিট তালিকা',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='প্রোডাক্ট নাম')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='মূল্য')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='স্টক')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='ডিসকাউন্ট (%)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='প্রোডাক্ট ছবি')),
                ('description', models.TextField(blank=True, verbose_name='বর্ণনা')),
                ('is_active', models.BooleanField(default=True, verbose_name='সক্রিয়')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='তৈরির সময়')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='আপডেট সময়')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_catalog.brand', verbose_name='ব্র্যান্ড')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_catalog.category', verbose_name='ক্যাটাগরি')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_catalog.unit', verbose_name='ইউনিট')),
            ],
            options={
                'verbose_name': 'প্রোডাক্ট',
                'verbose_name_plural': 'প্রোডাক্ট তালিকা',
                'ordering': ['-created_at'],
            },
        ),
    ]
