# Generated by Django 4.2.6 on 2025-12-26 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_items', to='diagnostics.testgroup')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_links', to='diagnostics.testitem')),
            ],
            options={
                'ordering': ['group', 'order'],
                'unique_together': {('group', 'item')},
            },
        ),
    ]
