# Generated by Django 4.2.6 on 2025-12-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_testgroupitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diagnostics.testgroup'),
        ),
    ]
