# Generated by Django 4.2.6 on 2025-12-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_alter_testitem_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='conversion_factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='testitem',
            name='math',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='testitem',
            name='unit2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
