# Generated by Django 4.2.6 on 2025-12-31 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_testitem_conversion_factor_testitem_math_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('visit', 'test_item')},
        ),
    ]
