# Generated by Django 4.2.6 on 2025-01-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_description', models.CharField(max_length=255)),
                ('brand_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('category_description', models.CharField(max_length=255)),
                ('cat_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ItemProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_sprice', models.TextField(max_length=50)),
                ('item_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
