# Generated by Django 4.2.6 on 2025-01-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembrand',
            name='brand_image',
            field=models.ImageField(default='images/default.png', upload_to='images/brand/'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='cat_image',
            field=models.ImageField(default='images/default.png', upload_to='images/category/'),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='item_image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/product/'),
        ),
    ]
