# Generated by Django 4.2.6 on 2025-01-12 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembrand',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itembrand'),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itemcategory'),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='item_description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='item_model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemproduct',
            name='item_pprice',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='item_sprice',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
