# Generated by Django 4.2.6 on 2025-01-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0002_itembrand_category_name_itemproduct_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduct',
            name='item_pprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='item_sprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
