# Generated by Django 4.2.6 on 2025-01-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0003_alter_itemproduct_item_pprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembrand',
            name='brand_image',
            field=models.ImageField(upload_to='images/brand/'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='cat_image',
            field=models.ImageField(upload_to='images/category/'),
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='item_image',
            field=models.ImageField(upload_to='images/product/'),
        ),
    ]
