# Generated by Django 4.2.6 on 2025-01-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0004_alter_itembrand_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduct',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product/'),
        ),
    ]
