# Generated by Django 4.2.6 on 2025-01-14 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0005_alter_itemproduct_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembrand',
            name='category_name',
        ),
    ]
