# Generated by Django 4.2.6 on 2025-01-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0006_alter_clients_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduct',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itembrand'),
        ),
    ]
