# Generated by Django 4.2.6 on 2025-01-20 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0008_itemunit_alter_itemproduct_itme_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemunit',
            old_name='Unit_description',
            new_name='unit_description',
        ),
        migrations.AlterField(
            model_name='itemproduct',
            name='itme_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itemunit'),
        ),
    ]
