# Generated by Django 4.2.6 on 2025-01-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0010_alter_purchaseorder_porder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='porder_status',
            field=models.CharField(choices=[('1', 'Received'), ('2', 'Pending'), ('3', 'Ordered'), ('4', 'Cancel')], default=3, max_length=1),
        ),
    ]
