# Generated by Django 4.2.6 on 2025-01-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0011_alter_purchaseorder_porder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduct',
            name='item_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
