# Generated by Django 4.2.6 on 2025-01-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0012_alter_itemproduct_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemproduct',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
    ]
