# Generated by Django 4.2.6 on 2025-02-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0016_rename_itme_qty_purchaseorderitem_item_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasepayment',
            old_name='payment_status',
            new_name='payment_type',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='porder_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
