# Generated by Django 4.2.6 on 2025-02-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0020_alter_purchaseorderitem_porder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemproduct',
            old_name='itme_alert_qty',
            new_name='item_alert_qty',
        ),
        migrations.RenameField(
            model_name='itemproduct',
            old_name='itme_barcode',
            new_name='item_barcode',
        ),
        migrations.RenameField(
            model_name='itemproduct',
            old_name='itme_sku',
            new_name='item_sku',
        ),
        migrations.RenameField(
            model_name='itemproduct',
            old_name='itme_status',
            new_name='item_status',
        ),
        migrations.RenameField(
            model_name='itemproduct',
            old_name='itme_unit',
            new_name='item_unit',
        ),
    ]
