# Generated by Django 4.2.6 on 2025-02-12 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0021_rename_itme_alert_qty_itemproduct_item_alert_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepayment',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='purchasepayment',
            name='payment_type',
            field=models.CharField(choices=[('1', 'Cash'), ('2', 'Card'), ('3', 'Others'), ('4', 'Due')], default=1, max_length=1),
        ),
    ]
