# Generated by Django 4.2.6 on 2025-02-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0024_service_serviceorder_stock_servicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='payment_status',
            field=models.CharField(choices=[('cash', 'Cash'), ('due', 'Due')], default='cash', max_length=10),
        ),
    ]
