# Generated by Django 4.2.6 on 2025-03-02 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0026_purchaseorder_barcode_purchasereturn_purchasecancel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='barcode',
        ),
    ]
