# Generated by Django 4.2.6 on 2025-03-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0027_remove_purchaseorder_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='porder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='return_item_sl', to='business_apps.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_qty', models.PositiveBigIntegerField(default=1)),
                ('item_pprice', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.itemproduct')),
                ('porder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.purchaseorder')),
            ],
        ),
    ]
