# Generated by Django 4.2.6 on 2025-03-08 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_apps', '0028_alter_purchaseorderitem_porder_id_purchasereturnitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturn',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='return_quantity',
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='porder_create_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='or_create_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='porder_create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='porder_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='porder_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='porder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='porder_note',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='porder_status',
            field=models.CharField(choices=[('1', 'Received'), ('2', 'Pending'), ('3', 'Ordered'), ('4', 'Cancel')], default=3, max_length=1),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='porder_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='porder_update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='or_create_update', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='porder_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
