# Generated by Django 4.2.6 on 2025-03-08 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business_apps', '0030_alter_purchaseorderitem_porder_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseReturnPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('payment_type', models.CharField(choices=[('1', 'Cash'), ('2', 'Card'), ('3', 'Due'), ('4', 'Others')], default=1, max_length=1)),
                ('payment_status', models.CharField(choices=[('cash', 'Cash'), ('due', 'Due')], default='cash', max_length=10)),
                ('payment_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('payment_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.purchaseorder')),
                ('payment_create_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_create_user', to=settings.AUTH_USER_MODEL)),
                ('payment_update_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_create_update', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
