# Generated by Django 4.2.6 on 2025-03-22 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_apps', '0031_purchasereturnpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturnitem',
            name='porder_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.purchasereturn'),
        ),
        migrations.AlterField(
            model_name='purchasereturnpayment',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='business_apps.purchasereturn'),
        ),
    ]
